### ISSUE TITLE
Bugs in learner.learn_invariants() / Is there a stable version?

### ISSUE THREAD

**Issue by vasylenson** [rindPHI/islearn#4]
Running `InvariantLeaner.learn_Invariants()` very closely following the example in the README, both on latest PyPI versions and on GitHub master and getting a crash with different errors.

My code, adapted from the README:

```py
from typing import Dict, Tuple

from islearn.parse_tree_utils import dfs, get_subtree, tree_to_string
from islearn.learner import InvariantLearner

from isla.language import DerivationTree
from isla.parser import EarleyParser
from isla.type_defs import ParseTree
from isla.language import ISLaUnparser, Formula


simple_grammar = {
    '<start>': ['<config>'],
    '<config>': ['<statement>', '<statement>; <config>'],
    '<statement>': ['<key>: <value>'],
    '<key>': ['name', 'date', 'time'],
    '<value>': list('0123456789'),
}


def parse_config(config: str) -> dict:
    entries = (e.split(': ') for e in config.split('; '))

    result = {}

    for index, entry in enumerate(entries):

        key, value = entry
        value = int(value)

        if key not in result:
            result[key] = value
        else:
            old = result[key]
            result[key] = max(old, value)


        if index > 2:
            return result
    
    raise Exception('too short')


def validate_lang(inp: DerivationTree) -> bool:
    try:
        parse_config(str(inp))
        return True
    except Exception:
        return False

result: Dict[Formula, Tuple[float, float]] = InvariantLearner(
    simple_grammar,
    prop=validate_lang,
    # activated_patterns={
    #     "Def-Use (reST Strict)",  # Optional; leads to quicker results
    # },
    # generate_new_learning_samples = False,
    # do_generate_more_inputs = False,
).learn_invariants()

print("\n".join(map(
    lambda p: f"{p[1]}: " + ISLaUnparser(p[0]).unparse(),
    {f: p for f, p in result.items() if p[0] > .0}.items())))
```

Note that the commented-out code is considered optional, however the errors come up when no `activated_patterns` is passed.

Traceback on the PyPI version:

```
Traceback (most recent call last):
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/test_islearn.py", line 59, in <module>
    ).learn_invariants()
      ^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 382, in learn_invariants
    candidates = self.generate_candidates(self.patterns, self.positive_examples_for_learning)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 636, in generate_candidates
    pattern_insts_without_mexpr_placeholders = self._filter_partial_instantiations(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 698, in _filter_partial_instantiations
    if not approximately_evaluate_abst_for(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1661, in approximately_evaluate_abst_for
    return ThreeValuedTruth.from_bool(all(
                                      ^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1662, in <genexpr>
    not approximately_evaluate_abst_for(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1656, in approximately_evaluate_abst_for
    return ThreeValuedTruth.from_bool(any(
                                      ^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1657, in <genexpr>
    not approximately_evaluate_abst_for(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1704, in approximately_evaluate_abst_for
    return ThreeValuedTruth.from_bool(all(
                                      ^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1705, in <genexpr>
    not approximately_evaluate_abst_for(sub_formula, grammar, graph, assignments, trie).is_false()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/islearn/learner.py", line 1543, in approximately_evaluate_abst_for
    for arg in translation[0]:
               ~~~~~~~~~~~^^^
TypeError: 'Success' object is not subscriptable
```

Traceback from the current master version:

```
Traceback (most recent call last):
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/test_islearn.py", line 98, in <module>
    ).learn_invariants()
      ^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 383, in learn_invariants
    candidates = self.generate_candidates(self.patterns, self.positive_examples_for_learning)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 637, in generate_candidates
    pattern_insts_without_mexpr_placeholders = self._filter_partial_instantiations(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 699, in _filter_partial_instantiations
    if not approximately_evaluate_abst_for(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1666, in approximately_evaluate_abst_for
    return ThreeValuedTruth.from_bool(all(
                                      ^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1667, in <genexpr>
    not approximately_evaluate_abst_for(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1661, in approximately_evaluate_abst_for
    return ThreeValuedTruth.from_bool(any(
                                      ^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1662, in <genexpr>
    not approximately_evaluate_abst_for(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1569, in approximately_evaluate_abst_for
    return approximately_evaluate_abst_for(formula.inner_formula, grammar, graph, assignments, trie)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1709, in approximately_evaluate_abst_for
    return ThreeValuedTruth.from_bool(all(
                                      ^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1710, in <genexpr>
    not approximately_evaluate_abst_for(sub_formula, grammar, graph, assignments, trie).is_false()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/learner.py", line 1689, in approximately_evaluate_abst_for
    eval_res = formula.predicate.evaluate(graph, *arg_insts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/lambda-interpreter/.venv/lib/python3.12/site-packages/isla/language.py", line 1103, in evaluate
    return self.eval_fun(graph, *instantiations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/islearn_predicates.py", line 182, in hex_to_dec
    decimal_str = str(hex_to_int(str(hexadecimal)))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markovasylenko/Documents/UT/thesis/code/islearn/src/islearn/islearn_predicates.py", line 101, in hex_to_int
    return int.from_bytes(bytearray.fromhex(hex_str), byteorder="big")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

Is this a stability problem? Could it be a mismatch between ISLa and ISLearn versions? Is there a version of the project where this functionality works?

Thank you!

**Comment by rindPHI** [comment]
Dear @vasylenson,

Thanks for your report.

The issue seems indeed to be due to an ISLa/ISLearn version mismatch. You may try downgrading ISLa to below the current PyPI version.

ISLearn is currently no longer actively maintained; pull requests are accepted. If you find a working ISLa version number, we can pin it in ISLearn to prevent this issue.

Cheers,
Dominic
